java_version=8
junit_version=5.10.0
assertj_version=3.24.2
jackson_version=2.17.2
encoding=UTF-8

github_org=jho951
github_repo=plugin-policy-engine

release_group=io.github.jho951
release_version=2.0.1

org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
