dependencies {
    // config가 사용자에게 제공하는 공개 API
    api project(":plugin-policy-engine-api")

    // 구현/내부용
    implementation("com.fasterxml.jackson.core:jackson-databind:${rootProject.config.jacksonVersion}")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:${rootProject.config.jacksonVersion}")
}
